- name: Install Keploy CLI
  run: |
    curl --silent -L https://keploy.io/ent/install.sh | bash

- name: Run Keploy Test Suite
  env:
    CI: true
    KEPLOY_API_KEY: ${{ secrets.KEPLOY_API_KEY }}
  run: | 
